#!/usr/bin/env python3
"""
Script to add incorrectOptionsFrench field to all word entries.
This maps the English incorrect options to their French translations.
"""

# Comprehensive French translation dictionary
translations = {
    # Animals
    "the dog": "le chien",
    "the mouse": "la souris",
    "the cat": "le chat",
    "the horse": "le cheval",
    "the apartment": "l'appartement",
    "the room": "la pièce",
    "the father": "le père",
    "the sister": "la sœur",
    "the mother": "la mère",
    "the brother": "le frère",
    "the cousin": "le cousin",
    "the uncle": "l'oncle",
    "the cake": "le gâteau",
    "the pastry": "la pâtisserie",
    "the milk": "le lait",
    "the juice": "le jus",
    "the water": "l'eau",
    "the coffee": "le café",
    "the pear": "la poire",
    "the orange": "l'orange",
    "the notebook": "le cahier",
    "the magazine": "le magazine",
    "the chair": "la chaise",
    "the desk": "le bureau",
    "the table": "la table",
    "the sofa": "le canapé",
    "the mattress": "le matelas",
    "the bus": "le bus",
    "the bicycle": "le vélo",
    "the motorcycle": "la moto",
    "the car": "la voiture",
    "the window": "la fenêtre",
    "the gate": "le portail",
    "the door": "la porte",
    "the balcony": "le balcon",
    "the park": "le parc",
    "the yard": "la cour",
    "the butterfly": "le papillon",
    "the bee": "l'abeille",
    "the shark": "le requin",
    "the dolphin": "le dauphin",
    "the town": "la ville",
    "the village": "le village",
    "the road": "la route",
    "the avenue": "l'avenue",
    "the tea": "le thé",
    "the hot chocolate": "le chocolat chaud",
    "the infusion": "l'infusion",
    "the fish": "le poisson",
    "the chicken": "le poulet",
    "the butter": "le beurre",
    "the yogurt": "le yaourt",
    "the candy": "le bonbon",
    "the cookie": "le biscuit",
    "the foot": "le pied",
    "the arm": "le bras",
    "the hand": "la main",
    "the leg": "la jambe",
    "the face": "le visage",
    "the neck": "le cou",
    "the ear": "l'oreille",
    "the nose": "le nez",
    "the lips": "les lèvres",
    "the mouth": "la bouche",
    "the chin": "le menton",
    "the colleague": "le collègue",
    "the neighbor": "le voisin",
    "the girl": "la fille",
    "the child": "l'enfant",
    "the boy": "le garçon",
    "the daughter": "la fille",
    "the woman": "la femme",
    "the gentleman": "le monsieur",
    "the man": "l'homme",
    "the lady": "la dame",
    "the baby": "le bébé",
    "the teenager": "l'adolescent",
    "the donkey": "l'âne",
    "the pony": "le poney",
    "the goat": "la chèvre",
    "the sheep": "le mouton",
    "the lamb": "l'agneau",
    "the turkey": "la dinde",
    "the duck": "le canard",
    "the café": "le café",
    "the bar": "le bar",
    "the university": "l'université",
    "the college": "le collège",
    "the market": "le marché",
    "the shop": "la boutique",
    "the vegetable": "le légume",
    "the berry": "la baie",

    # Verbs
    "to have": "avoir",
    "to become": "devenir",
    "to be": "être",
    "to hold": "tenir",
    "to come": "venir",
    "to leave": "partir",
    "to create": "créer",
    "to produce": "produire",
    "to speak": "parler",
    "to talk": "parler",
    "to want": "vouloir",
    "to must": "devoir",
    "to wish": "souhaiter",
    "to desire": "désirer",
    "to need": "avoir besoin",
    "to should": "devoir",
    "to know (people)": "connaître",
    "to learn": "apprendre",
    "to know (facts)": "savoir",
    "to meet": "rencontrer",
    "to drink": "boire",
    "to taste": "goûter",
    "to eat": "manger",
    "to swallow": "avaler",
    "to rest": "se reposer",
    "to nap": "faire la sieste",
    "to say": "dire",
    "to chat": "bavarder",
    "to hear": "entendre",
    "to understand": "comprendre",
    "to see": "voir",
    "to observe": "observer",
    "to watch": "regarder",
    "to look": "regarder",
    "to listen": "écouter",
    "to know": "savoir",
    "to teach": "enseigner",
    "to study": "étudier",
    "to write": "écrire",
    "to type": "taper",
    "to read": "lire",
    "to go": "aller",
    "to arrive": "arriver",
    "to depart": "partir",
    "to reach": "atteindre",
    "to go in": "entrer",
    "to come in": "entrer",
    "to escape": "s'échapper",
    "to go down": "descendre",
    "to rise": "monter",
    "to go up": "monter",
    "to fall": "tomber",
    "to wait": "attendre",
    "to reside": "résider",
    "to dwell": "habiter",
    "to labor": "travailler",
    "to function": "fonctionner",
    "to game": "jouer",
    "to perform": "jouer",
    "to adore": "adorer",
    "to prefer": "préférer",
    "to dislike": "ne pas aimer",
    "to despise": "mépriser",
    "to like better": "préférer",
    "to favor": "favoriser",
    "to find": "trouver",
    "to seek": "chercher",
    "to search": "chercher",
    "to discover": "découvrir",
    "to offer": "offrir",
    "to provide": "fournir",
    "to grab": "saisir",
    "to seize": "saisir",
    "to set": "mettre",
    "to lay": "poser",
    "to purchase": "acheter",
    "to acquire": "acquérir",
    "to buy": "acheter",
    "to trade": "échanger",
    "to spend": "dépenser",
    "to cost": "coûter",
    "to open": "ouvrir",
    "to unlock": "déverrouiller",
    "to shut": "fermer",
    "to lock": "verrouiller",
    "to begin": "commencer",
    "to start": "commencer",
    "to end": "finir",
    "to terminate": "terminer",
    "to call": "appeler",
    "to phone": "téléphoner",
    "to answer": "répondre",
    "to reply": "répondre",
    "to request": "demander",
    "to inquire": "demander",
    "to respond": "répondre",
    "to react": "réagir",
    "to try": "essayer",
    "to attempt": "essayer",
    "to succeed": "réussir",
    "to achieve": "réussir",
    "to think": "penser",
    "to believe": "croire",
    "to hope": "espérer",
    "to wish for": "souhaiter",
    "to forget": "oublier",
    "to lose memory": "oublier",
    "to recall": "se souvenir",
    "to recollect": "se rappeler",
    "to wait for": "attendre",
    "to expect": "attendre",
    "to search for": "chercher",
    "to seek for": "chercher",
    "to utilize": "utiliser",
    "to employ": "utiliser",
    "to assist": "aider",
    "to support": "aider",
    "to ask": "demander",
    "to inquire about": "demander",
    "to deliver": "apporter",
    "to bring": "apporter",
    "to fetch": "aller chercher",
    "to get": "obtenir",
    "to send": "envoyer",
    "to mail": "envoyer",
    "to receive": "recevoir",
    "to accept": "accepter",
    "to turn": "tourner",
    "to rotate": "tourner",
    "to push": "pousser",
    "to shove": "pousser",
    "to tug": "tirer",
    "to drag": "tirer",
    "to stop": "arrêter",
    "to halt": "arrêter",
    "to continue": "continuer",
    "to proceed": "continuer",
    "to run": "courir",
    "to jog": "courir",
    "to stroll": "se promener",
    "to wander": "se promener",
    "to leap": "sauter",
    "to hop": "sauter",
    "to drop": "tomber",
    "to collapse": "tomber",
    "to raise": "lever",
    "to lift": "lever",
    "to lower": "baisser",
    "to reduce": "baisser",
    "to shut down": "fermer",
    "to close down": "fermer",
    "to launch": "ouvrir",
    "to start up": "ouvrir",
    "to wash": "laver",
    "to clean": "nettoyer",
    "to dry": "sécher",
    "to wipe": "essuyer",
    "to cook": "cuisiner",
    "to prepare food": "cuisiner",
    "to prepare": "préparer",
    "to get ready": "préparer",
    "to build": "construire",
    "to construct": "construire",
    "to destroy": "détruire",
    "to demolish": "détruire",
    "to alter": "changer",
    "to modify": "changer",
    "to remain": "rester",
    "to stay the same": "rester",
    "to awaken": "se réveiller",
    "to wake": "se réveiller",
    "to get up": "se lever",
    "to arise": "se lever",
    "to get dressed": "s'habiller",
    "to dress": "s'habiller",
    "to undress": "se déshabiller",
    "to disrobe": "se déshabiller",
    "to bathe": "se laver",
    "to shower": "se doucher",
    "to groom": "se préparer",
    "to prepare oneself": "se préparer",
    "to sit down": "s'asseoir",
    "to take a seat": "s'asseoir",
    "to stand": "se lever",
    "to get to one's feet": "se lever",
    "to recline": "se coucher",
    "to lie down": "se coucher",
    "to hurry": "se dépêcher",
    "to rush": "se dépêcher",
    "to relax": "se détendre",
    "to unwind": "se détendre",
    "to have fun": "s'amuser",
    "to enjoy oneself": "s'amuser",
    "to get bored": "s'ennuyer",
    "to be bored": "s'ennuyer",
    "to stroll around": "se promener",
    "to walk around": "se promener",

    # Adjectives
    "big": "grand",
    "large": "grand",
    "little": "petit",
    "tiny": "petit",
    "tall": "grand",
    "high": "haut",
    "low": "bas",
    "short": "court",
    "long": "long",
    "lengthy": "long",
    "short (height)": "court",
    "brief": "court",
    "wide": "large",
    "broad": "large",
    "narrow": "étroit",
    "slim": "mince",
    "fat": "gros",
    "heavy": "lourd",
    "light": "léger",
    "lightweight": "léger",
    "old": "vieux",
    "ancient": "vieux",
    "young": "jeune",
    "youthful": "jeune",
    "new": "nouveau",
    "recent": "nouveau",
    "modern": "moderne",
    "contemporary": "moderne",
    "good": "bon",
    "fine": "bon",
    "bad": "mauvais",
    "poor": "mauvais",
    "nice": "gentil",
    "kind": "gentil",
    "mean": "méchant",
    "cruel": "méchant",
    "happy": "heureux",
    "joyful": "heureux",
    "sad": "triste",
    "unhappy": "triste",
    "beautiful": "beau",
    "lovely": "beau",
    "ugly": "laid",
    "unattractive": "laid",
    "hot": "chaud",
    "warm": "chaud",
    "cold": "froid",
    "chilly": "froid",
    "easy": "facile",
    "simple": "facile",
    "hard": "difficile",
    "complicated": "difficile",
    "fast": "rapide",
    "quick": "rapide",
    "slow": "lent",
    "sluggish": "lent",
    "strong": "fort",
    "powerful": "fort",
    "weak": "faible",
    "feeble": "faible",
    "full": "plein",
    "filled": "plein",
    "empty": "vide",
    "vacant": "vide",
    "clean": "propre",
    "neat": "propre",
    "dirty": "sale",
    "filthy": "sale",
    "rich": "riche",
    "wealthy": "riche",
    "poor (wealth)": "pauvre",
    "impoverished": "pauvre",
    "expensive": "cher",
    "costly": "cher",
    "cheap": "bon marché",
    "inexpensive": "bon marché",
    "near": "proche",
    "close": "proche",
    "far": "loin",
    "distant": "loin",
    "right": "juste",
    "correct": "correct",
    "wrong": "faux",
    "incorrect": "incorrect",
    "same": "même",
    "identical": "identique",
    "different": "différent",
    "distinct": "différent",
    "open": "ouvert",
    "unlocked": "ouvert",
    "closed": "fermé",
    "shut": "fermé",
    "ready": "prêt",
    "prepared": "prêt",
    "late": "en retard",
    "tardy": "en retard",
    "early": "en avance",
    "ahead of time": "en avance",
    "punctual": "à l'heure",
    "on time": "à l'heure",
    "sick": "malade",
    "ill": "malade",
    "healthy": "en bonne santé",
    "well": "bien",
    "tired": "fatigué",
    "exhausted": "fatigué",
    "energetic": "énergique",
    "active": "actif",
    "hungry": "avoir faim",
    "famished": "avoir faim",
    "thirsty": "avoir soif",
    "parched": "avoir soif",
    "afraid": "avoir peur",
    "scared": "avoir peur",
    "brave": "courageux",
    "courageous": "courageux",
    "intelligent": "intelligent",
    "smart": "intelligent",
    "stupid": "stupide",
    "dumb": "bête",
    "interesting": "intéressant",
    "fascinating": "intéressant",
    "boring": "ennuyeux",
    "dull": "ennuyeux",
    "important": "important",
    "significant": "important",
    "unimportant": "pas important",
    "insignificant": "insignifiant",
    "possible": "possible",
    "feasible": "possible",
    "impossible": "impossible",
    "unfeasible": "impossible",
    "true": "vrai",
    "genuine": "vrai",
    "false": "faux",
    "untrue": "faux",
    "sure": "sûr",
    "certain": "certain",
    "unsure": "pas sûr",
    "uncertain": "incertain",
    "necessary": "nécessaire",
    "essential": "essentiel",
    "unnecessary": "pas nécessaire",
    "needless": "inutile",
    "dangerous": "dangereux",
    "risky": "dangereux",
    "safe": "sûr",
    "secure": "sécurisé",

    # Colors
    "red": "rouge",
    "crimson": "rouge",
    "blue": "bleu",
    "azure": "bleu",
    "green": "vert",
    "emerald": "vert",
    "yellow": "jaune",
    "golden": "jaune",
    "black": "noir",
    "dark": "noir",
    "white": "blanc",
    "pale": "blanc",
    "orange": "orange",
    "tangerine": "orange",
    "purple": "violet",
    "violet": "violet",
    "pink": "rose",
    "rosy": "rose",
    "brown": "marron",
    "tan": "marron",
    "gray": "gris",
    "grey": "gris",

    # Numbers and quantities
    "one": "un",
    "a single": "un",
    "two": "deux",
    "a pair": "deux",
    "three": "trois",
    "a trio": "trois",
    "four": "quatre",
    "a quartet": "quatre",
    "five": "cinq",
    "a quintet": "cinq",
    "six": "six",
    "half dozen": "six",
    "seven": "sept",
    "a week": "sept",
    "eight": "huit",
    "an octet": "huit",
    "nine": "neuf",
    "a nonet": "neuf",
    "ten": "dix",
    "a decade": "dix",
    "eleven": "onze",
    "a dozen minus one": "onze",
    "twelve": "douze",
    "a dozen": "douze",
    "thirteen": "treize",
    "a baker's dozen": "treize",
    "fourteen": "quatorze",
    "two weeks": "quatorze",
    "fifteen": "quinze",
    "a fortnight": "quinze",
    "sixteen": "seize",
    "sweet sixteen": "seize",
    "seventeen": "dix-sept",
    "a teen": "dix-sept",
    "eighteen": "dix-huit",
    "legal age": "dix-huit",
    "nineteen": "dix-neuf",
    "almost twenty": "dix-neuf",
    "twenty": "vingt",
    "a score": "vingt",
    "thirty": "trente",
    "thrice ten": "trente",
    "forty": "quarante",
    "four tens": "quarante",
    "fifty": "cinquante",
    "half hundred": "cinquante",
    "sixty": "soixante",
    "six tens": "soixante",
    "seventy": "soixante-dix",
    "seven tens": "soixante-dix",
    "eighty": "quatre-vingts",
    "eight tens": "quatre-vingts",
    "ninety": "quatre-vingt-dix",
    "nine tens": "quatre-vingt-dix",
    "one hundred": "cent",
    "a century": "cent",
    "one thousand": "mille",
    "a grand": "mille",

    # Time expressions
    "today": "aujourd'hui",
    "this day": "aujourd'hui",
    "yesterday": "hier",
    "the day before": "hier",
    "tomorrow": "demain",
    "the next day": "demain",
    "now": "maintenant",
    "at present": "maintenant",
    "later": "plus tard",
    "afterwards": "plus tard",
    "before": "avant",
    "earlier": "avant",
    "after": "après",
    "following": "après",
    "always": "toujours",
    "forever": "toujours",
    "never": "jamais",
    "not ever": "jamais",
    "sometimes": "quelquefois",
    "occasionally": "parfois",
    "often": "souvent",
    "frequently": "souvent",
    "rarely": "rarement",
    "seldom": "rarement",
    "already": "déjà",
    "by now": "déjà",
    "still": "encore",
    "yet": "encore",
    "soon": "bientôt",
    "shortly": "bientôt",
    "late": "tard",
    "behind schedule": "tard",
    "early (time)": "tôt",
    "ahead of schedule": "tôt",

    # Common phrases and expressions
    "hello": "bonjour",
    "hi": "salut",
    "goodbye": "au revoir",
    "bye": "au revoir",
    "please": "s'il vous plaît",
    "kindly": "s'il vous plaît",
    "thank you": "merci",
    "thanks": "merci",
    "you're welcome": "de rien",
    "no problem": "de rien",
    "sorry": "désolé",
    "excuse me": "excusez-moi",
    "yes": "oui",
    "yeah": "oui",
    "no": "non",
    "nope": "non",
    "maybe": "peut-être",
    "perhaps": "peut-être",
    "how are you (formal)": "comment allez-vous",
    "what's up": "quoi de neuf",
    "I don't know": "je ne sais pas",
    "I'm not sure": "je ne suis pas sûr",
    "I understand": "je comprends",
    "I get it": "je comprends",
    "I don't understand": "je ne comprends pas",
    "I'm confused": "je suis confus",
    "of course": "bien sûr",
    "naturally": "bien sûr",
    "that's right": "c'est ça",
    "exactly": "exactement",

    # Question words
    "what": "quoi",
    "which": "quel",
    "who": "qui",
    "whom": "qui",
    "where": "où",
    "in what place": "où",
    "when": "quand",
    "at what time": "quand",
    "why": "pourquoi",
    "for what reason": "pourquoi",
    "how": "comment",
    "in what way": "comment",
    "how much": "combien",
    "what amount": "combien",
    "how many": "combien de",
    "what number": "combien",

    # Prepositions and conjunctions
    "in": "dans",
    "inside": "dans",
    "on": "sur",
    "upon": "sur",
    "at": "à",
    "by": "à",
    "with": "avec",
    "alongside": "avec",
    "without": "sans",
    "lacking": "sans",
    "for": "pour",
    "in favor of": "pour",
    "against": "contre",
    "opposed to": "contre",
    "under": "sous",
    "beneath": "sous",
    "over": "sur",
    "above": "au-dessus",
    "between": "entre",
    "among": "parmi",
    "through": "à travers",
    "via": "par",
    "to": "à",
    "toward": "vers",
    "from": "de",
    "away from": "de",
    "of": "de",
    "belonging to": "de",
    "about": "sur",
    "concerning": "concernant",
    "during": "pendant",
    "throughout": "pendant",
    "since": "depuis",
    "from the time": "depuis",
    "until": "jusqu'à",
    "till": "jusqu'à",
    "and": "et",
    "also": "et",
    "but": "mais",
    "however": "mais",
    "or": "ou",
    "alternatively": "ou",
    "because": "parce que",
    "since (reason)": "parce que",
    "if": "si",
    "in case": "si",
    "then": "alors",
    "therefore": "donc",
    "so": "donc",
    "thus": "donc",
    "as": "comme",
    "like": "comme",
    "than": "que",
    "compared to": "que",

    # Pronouns
    "I": "je",
    "me": "moi",
    "you": "tu",
    "thou": "tu",
    "he": "il",
    "him": "lui",
    "she": "elle",
    "her": "elle",
    "we": "nous",
    "us": "nous",
    "you (plural)": "vous",
    "y'all": "vous",
    "they": "ils",
    "them": "eux",
    "this": "ce",
    "this one": "ceci",
    "that": "ça",
    "that one": "cela",
    "these": "ces",
    "those": "ceux",
    "something": "quelque chose",
    "anything": "quelque chose",
    "nothing": "rien",
    "naught": "rien",
    "everything": "tout",
    "all": "tout",
    "someone": "quelqu'un",
    "anybody": "quelqu'un",
    "no one": "personne",
    "nobody": "personne",
    "everyone": "tout le monde",
    "everybody": "tout le monde",

    # Adverbs
    "well (adverb)": "bien",
    "nicely": "bien",
    "badly": "mal",
    "poorly": "mal",
    "very": "très",
    "extremely": "très",
    "too": "trop",
    "excessively": "trop",
    "enough": "assez",
    "sufficiently": "assez",
    "more": "plus",
    "additional": "plus",
    "less": "moins",
    "fewer": "moins",
    "most": "le plus",
    "greatest": "le plus",
    "least": "le moins",
    "smallest": "le moins",
    "much": "beaucoup",
    "a lot": "beaucoup",
    "little (quantity)": "peu",
    "not much": "peu",
    "many": "beaucoup de",
    "numerous": "nombreux",
    "few": "peu de",
    "not many": "peu de",
    "here": "ici",
    "in this place": "ici",
    "there": "là",
    "in that place": "là",
    "everywhere": "partout",
    "all places": "partout",
    "nowhere": "nulle part",
    "no place": "nulle part",
    "together": "ensemble",
    "jointly": "ensemble",
    "alone": "seul",
    "by oneself": "seul",
    "again": "encore",
    "once more": "encore",
    "also (adverb)": "aussi",
    "too (adverb)": "aussi",
    "only": "seulement",
    "just": "seulement",
    "almost": "presque",
    "nearly": "presque",
    "quite": "assez",
    "fairly": "assez",
    "really": "vraiment",
    "truly": "vraiment",
    "maybe (adverb)": "peut-être",
    "possibly": "peut-être",
    "certainly (adverb)": "certainement",
    "surely": "certainement",
    "probably": "probablement",
    "likely": "probablement",
    "unfortunately": "malheureusement",
    "sadly": "malheureusement",
    "fortunately": "heureusement",
    "luckily": "heureusement",
    "finally": "enfin",
    "at last": "enfin",
    "finally (end)": "finalement",
    "in the end": "finalement",
    "firstly": "premièrement",
    "first": "premièrement",
    "in the first place": "en premier lieu",
    "secondly": "deuxièmement",
    "second": "deuxièmement",
    "in the second place": "en deuxième lieu",
    "regrettably": "malheureusement",
    "happily": "heureusement",
    "thankfully": "heureusement",
    "presumably": "probablement",
    "definitely": "certainement",
    "clearly": "clairement",
    "apparently": "apparemment",
    "seemingly": "apparemment",
    "evidently": "évidemment",
    "indeed": "en effet",
    "actually": "en fait",
    "completely": "complètement",
    "totally": "totalement",
    "entirely": "entièrement",
    "wholly": "totalement",
    "especially": "surtout",
    "specifically": "spécifiquement",
    "particularly": "particulièrement",
    "mainly": "principalement",
    "chiefly": "principalement",
    "principally": "principalement",
    "usually": "habituellement",
    "typically": "typiquement",
    "generally": "généralement",
    "lately": "récemment",
    "not long ago": "récemment",
    "before long": "bientôt",
    "once": "autrefois",
    "previously": "auparavant",

    # Possessive adjectives and misc
    "my": "mon",
    "mine": "le mien",
    "your": "ton",
    "yours": "le tien",
    "his": "son",
    "his own": "le sien",
    "her (possessive)": "son",
    "hers": "le sien",
    "our": "notre",
    "ours": "le nôtre",
    "your (plural possessive)": "votre",
    "yours (plural)": "le vôtre",
    "their": "leur",
    "theirs": "le leur",

    # Misc nouns
    "the store": "le magasin",
    "the city": "la ville",
    "the street": "la rue",
    "the bread": "le pain",
    "the apple": "la pomme",
    "the book": "le livre",
    "the bed": "le lit",
    "the garden": "le jardin",
    "the bird": "l'oiseau",
    "the coffee (noun)": "le café",
    "the tea (noun)": "le thé",
    "the meat": "la viande",
    "the cheese": "le fromage",
    "the chocolate": "le chocolat",
    "the eye": "l'œil",
    "the friend (male)": "l'ami",
    "the friend (female)": "l'amie",
    "the horse (noun)": "le cheval",
    "the cow": "la vache",
    "the sheep (noun)": "le mouton",
    "the chicken (noun)": "le poulet",
    "the restaurant": "le restaurant",
    "the school": "l'école",
    "the fruit": "le fruit",
    "the house": "la maison",
    "the mother (noun)": "la mère",
    "the father (noun)": "le père",
    "the sister (noun)": "la sœur",
    "the brother (noun)": "le frère",
    "the water (noun)": "l'eau",
    "the milk (noun)": "le lait",
}

def read_file():
    """Read the original words.ts file"""
    with open(r'c:\Source\french\src\data\words.ts', 'r', encoding='utf-8') as f:
        return f.read()

def get_french_translation(english_option):
    """Get the French translation for an English option"""
    # Direct lookup
    if english_option in translations:
        return translations[english_option]

    # If not found, try to infer based on similar patterns
    # This should not happen if the translation dictionary is complete
    print(f"WARNING: No translation found for: '{english_option}'")
    return f"[MISSING: {english_option}]"

def process_line(line):
    """Process a single line and add incorrectOptionsFrench if it's a word entry"""
    line = line.strip()

    # Skip non-entry lines
    if not line.startswith('{ id:'):
        return line

    # Check if incorrectOptionsFrench already exists
    if 'incorrectOptionsFrench:' in line:
        return line

    # Extract incorrectOptions
    import re
    match = re.search(r'incorrectOptions:\s*\[(.*?)\]', line)
    if not match:
        return line

    options_str = match.group(1)
    # Parse the two options
    options = re.findall(r'"([^"]*)"', options_str)

    if len(options) != 2:
        print(f"WARNING: Expected 2 incorrect options but found {len(options)}: {options}")
        return line

    # Get French translations
    french_option1 = get_french_translation(options[0])
    french_option2 = get_french_translation(options[1])

    # Find where to insert the new field (after incorrectOptions)
    # We want to insert it before the level field
    insert_pos = line.find(', level:')
    if insert_pos == -1:
        print(f"WARNING: Could not find ', level:' in line: {line}")
        return line

    # Construct the new field
    french_field = f', incorrectOptionsFrench: ["{french_option1}", "{french_option2}"]'

    # Insert the new field
    new_line = line[:insert_pos] + french_field + line[insert_pos:]

    return new_line

def main():
    """Main function to update the words.ts file"""
    print("Reading words.ts file...")
    content = read_file()

    print("Processing lines...")
    lines = content.split('\n')
    new_lines = []

    for line in lines:
        new_line = process_line(line)
        new_lines.append(new_line)

    new_content = '\n'.join(new_lines)

    print("Writing updated file...")
    with open(r'c:\Source\french\src\data\words.ts', 'w', encoding='utf-8') as f:
        f.write(new_content)

    print("Done! All word entries have been updated with incorrectOptionsFrench field.")

if __name__ == '__main__':
    main()
